apiVersion: v1
kind: Secret
metadata:
  name: cli
type: Opaque
data:
  sawtooth-pub-key: MDI1OTM4MDFkNzgzMDI2MmNlZDEwZDVkMjk5ZDYyODg0MmNmZDM1MTE3YWExZjc0NzRmZDBjZDJkYzcxYzk5Y2Jm
  sawtooth-priv-key: YjZkN2YwMjM4YTUzNzkwNTc1MDM0MDFhOWVjNTk2ZTUzYmUzNWY0NjhmM2JjYzZmODQ4NDEyY2YzMjNkOGI1Mg==