apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  CONSENSOURCEDB_NAME: Y29uc2Vuc291cmNlZGI=
  CONSENSOURCEDB_USER: Y29uc2Vuc291cmNlZGI=
  CONSENSOURCEDB_PASSWORD: Y29uc2Vuc291cmNlZGI=