apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgresdb-service
    app: postgres-db
  name: postgresdb-service
spec:
  ports:
    - name: pg-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
     app: postgres-db
